version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: desafio-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_DATABASE: desafioscteciaparadevs
    restart: unless-stopped
    networks:
      - desafio-network

volumes:
  mongodb_data:
  mongodb_config:

networks:
  desafio-network:
    driver: bridge
